import type { Locale } from "@/i18n/config";

// Printable worksheets (lead magnets beyond the shortcut articles).
// Each one is a PDF in public/downloads generated by
// scripts/cheatsheets/build.ts from this registry plus the layout and
// finger data in src/lib. The resources hub lists them; gated ones sit
// behind the email form, the rest download directly.

export type WorksheetId =
  | "finger-map"
  | "blank-layout"
  | "tracker"
  | "numpad"
  | "poster"
  | "self-test"
  | "special-chars";

export type Worksheet = {
  id: WorksheetId;
  gated: boolean;
  file: Record<Locale, string>;
  title: Record<Locale, string>;
  description: Record<Locale, string>;
};

export const worksheets: Worksheet[] = [
  {
    id: "finger-map",
    gated: true,
    file: { de: "finger-tastatur-karte-qwertz", en: "finger-keyboard-map-qwerty", fr: "carte-doigts-clavier-azerty" },
    title: {
      de: "Finger-Tastatur-Karte (QWERTZ)",
      en: "Finger keyboard map (QWERTY)",
      fr: "Carte doigts-clavier (AZERTY)",
    },
    description: {
      de: "Welcher Finger tippt welche Taste: Tastatur mit Farbzonen, beide Hände, Grundstellung. Neben die Tastatur legen.",
      en: "Which finger hits which key: color zones, both hands, home position. Keep it next to your keyboard.",
      fr: "Quel doigt frappe quelle touche : zones de couleur, les deux mains, position de base. À poser à côté du clavier.",
    },
  },
  {
    id: "blank-layout",
    gated: false,
    file: { de: "leeres-layout-qwertz", en: "blank-layout-qwerty", fr: "clavier-vierge-azerty" },
    title: {
      de: "Leeres Layout zum Ausfüllen (QWERTZ)",
      en: "Blank layout to fill in (QWERTY)",
      fr: "Clavier vierge à compléter (AZERTY)",
    },
    description: {
      de: "Trockentraining: alle Buchstaben aus dem Gedächtnis eintragen. Zeigt in zwei Minuten, welche Tasten noch nicht sitzen.",
      en: "Dry run: fill in every letter from memory. Shows in two minutes which keys you still have to look for.",
      fr: "Entraînement à sec : place toutes les lettres de mémoire. En deux minutes, tu vois quelles touches ne sont pas encore acquises.",
    },
  },
  {
    id: "tracker",
    gated: true,
    file: { de: "fortschritts-tracker-4-wochen", en: "progress-tracker-4-weeks", fr: "suivi-progression-4-semaines" },
    title: {
      de: "Fortschritts-Tracker: 4 Wochen",
      en: "Progress tracker: 4 weeks",
      fr: "Suivi de progression : 4 semaines",
    },
    description: {
      de: "28 Tage, eine Zeile pro Übungstag: Lektion, WPM, Genauigkeit, Minuten. Mit Startwert und Wochenziel.",
      en: "28 days, one line per practice day: lesson, WPM, accuracy, minutes. With starting value and weekly goal.",
      fr: "28 jours, une ligne par séance : leçon, MPM, précision, minutes. Avec valeur de départ et objectif hebdomadaire.",
    },
  },
  {
    id: "numpad",
    gated: true,
    file: { de: "nummernblock-karte", en: "numpad-map", fr: "carte-pave-numerique" },
    title: {
      de: "Nummernblock-Karte",
      en: "Numpad map",
      fr: "Carte du pavé numérique",
    },
    description: {
      de: "Fingerzuordnung auf dem Ziffernblock, Grundstellung 4-5-6. Für Buchhaltung, Verwaltung, Tabellen.",
      en: "Finger assignment on the numeric keypad, home position 4-5-6. For accounting, admin work, spreadsheets.",
      fr: "Position des doigts sur le pavé numérique, base 4-5-6. Pour la comptabilité, l'administration, les tableurs.",
    },
  },
  {
    id: "poster",
    gated: true,
    file: { de: "poster-welcher-finger-tippt-was-qwertz", en: "poster-which-finger-types-what-qwerty", fr: "affiche-quel-doigt-tape-quoi-azerty" },
    title: {
      de: "Büro-Poster: Welcher Finger tippt was?",
      en: "Office poster: which finger types what?",
      fr: "Affiche bureau : quel doigt tape quoi ?",
    },
    description: {
      de: "Große Tastatur mit Farbzonen, kaum Text. Für die Wand im Büro, im Homeoffice oder im Schulungsraum.",
      en: "Big color-zoned keyboard, hardly any text. For the office wall, the home office or the training room.",
      fr: "Grand clavier à zones de couleur, presque sans texte. Pour le mur du bureau, du télétravail ou de la salle de formation.",
    },
  },
  {
    id: "self-test",
    gated: true,
    file: { de: "selbsttest-wo-stehst-du", en: "self-test-where-do-you-stand", fr: "auto-evaluation-ou-en-es-tu" },
    title: {
      de: "Selbsttest: Wo stehst du?",
      en: "Self-test: where do you stand?",
      fr: "Auto-évaluation : où en es-tu ?",
    },
    description: {
      de: "Acht Fragen zum Ankreuzen, Auswertung in drei Stufen und der passende Einstieg für jede Stufe.",
      en: "Eight yes/no questions, a three-level result and the right starting point for each level.",
      fr: "Huit questions à cocher, un résultat en trois niveaux et le bon point de départ pour chacun.",
    },
  },
  {
    id: "special-chars",
    gated: true,
    file: { de: "sonderzeichen-karte-qwertz", en: "special-characters-qwerty", fr: "caracteres-speciaux-azerty" },
    title: {
      de: "Sonderzeichen-Karte (QWERTZ)",
      en: "Special characters (QWERTY)",
      fr: "Caractères spéciaux (AZERTY)",
    },
    description: {
      de: "@, €, %, /, {, }, |, ~ und Co.: welche Taste, welche Umschalttaste, welcher Finger.",
      en: "@, #, %, /, {, }, |, ~ and friends: which key, which modifier, which finger.",
      fr: "@, €, %, /, {, }, |, ~ et compagnie : quelle touche, quel modificateur, quel doigt.",
    },
  },
];

export function worksheetUrl(sheet: Worksheet, locale: Locale): string {
  return `/downloads/${sheet.file[locale]}.pdf`;
}
