import type { Lesson, LessonMeta } from "./types";

// German QWERTZ curriculum.
// Key unlock order follows German letter frequency and QWERTZ physical layout:
// home row ends with ö (right pinky), z sits in the top row, y in the bottom row.
// Every drill uses ONLY keys that have been unlocked up to that lesson.

const HOME_ROW = ["a", "s", "d", "f", "g", "h", "j", "k", "l", "ö", " "];
const TOP_ROW = ["q", "w", "e", "r", "t", "z", "u", "i", "o", "p", "ü"];
const BOTTOM_ROW = ["y", "x", "c", "v", "b", "n", "m", ",", ".", "-"];
const ALL_LETTERS = [...HOME_ROW, ...TOP_ROW, ...BOTTOM_ROW, "ä", "ß"];

export const lessons: Lesson[] = [
  // === Phase 0: Einführung ===
  {
    id: 0,
    phase: 0,
    newKeys: ["f", "j"],
    allKeys: ["f", "j", " "],
    drills: [
      { type: "keys", content: "f j f j f j j f j f f j" },
      { type: "keys", content: "ff jj fj jf ff jj fj jf" },
      { type: "keys", content: "fjf jfj fjf jfj fjf jfj" },
    ],
    completionThreshold: 90,
    isFree: true,
  },
  // === Phase 1: Grundreihe ===
  {
    id: 1,
    phase: 1,
    newKeys: ["f", "j"],
    allKeys: ["f", "j", " "],
    drills: [
      { type: "keys", content: "f j f j j f f j j f j f f j" },
      { type: "keys", content: "ff jj ff jj fj fj jf jf fjf jfj" },
      { type: "keys", content: "fj jf ffj jjf fjj jff fjfj jfjf" },
    ],
    completionThreshold: 90,
    isFree: true,
  },
  {
    id: 2,
    phase: 1,
    newKeys: ["d", "k"],
    allKeys: ["f", "j", "d", "k", " "],
    drills: [
      { type: "keys", content: "d k d k k d d k k d d k" },
      { type: "keys", content: "fd jk df kj fdk jkf dkf" },
      { type: "keys", content: "dd kk dk kd fdk kjf dkfj" },
    ],
    completionThreshold: 90,
    isFree: true,
  },
  {
    id: 3,
    phase: 1,
    newKeys: ["s", "l"],
    allKeys: ["f", "j", "d", "k", "s", "l", " "],
    drills: [
      { type: "keys", content: "s l s l l s s l l s s l" },
      { type: "keys", content: "sd lk fs jl ds kl fds jkl" },
      { type: "keys", content: "sl ls ssl lls fsl jkl dsl skl" },
    ],
    completionThreshold: 90,
    isFree: true,
  },
  {
    id: 4,
    phase: 1,
    newKeys: ["a", "ö"],
    allKeys: ["a", "s", "d", "f", "j", "k", "l", "ö", " "],
    drills: [
      { type: "keys", content: "a ö a ö ö a a ö a ö ö a" },
      { type: "keys", content: "as öl df jk sa lö fd kj" },
      { type: "words", content: "ja das als fass lass dass saal öl" },
    ],
    completionThreshold: 90,
    isFree: true,
  },
  {
    id: 5,
    phase: 1,
    newKeys: ["g", "h"],
    allKeys: [...HOME_ROW],
    drills: [
      { type: "keys", content: "g h g h h g g h g h h g" },
      { type: "words", content: "gas sag hals glas lag sah aha gag" },
      { type: "words", content: "jagd saga gala sag das glas hals ja" },
    ],
    completionThreshold: 90,
    isFree: true,
  },
  // === Phase 2: Obere Reihe ===
  {
    id: 6,
    phase: 2,
    newKeys: ["e", "i"],
    allKeys: [...HOME_ROW, "e", "i"],
    drills: [
      { type: "keys", content: "e i e i i e e i i e e i" },
      { type: "keys", content: "de ki ed ik fe ei sei die" },
      { type: "words", content: "die sie eis seide leise hilfe geige fliege" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 7,
    phase: 2,
    newKeys: ["r", "u"],
    allKeys: [...HOME_ROW, "e", "i", "r", "u"],
    drills: [
      { type: "keys", content: "r u r u u r r u u r r u" },
      { type: "keys", content: "fr ju ur ru er re dur ruf" },
      { type: "words", content: "der du uhr rede reise dauer feuer freude erde" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 8,
    phase: 2,
    newKeys: ["t", "z"],
    allKeys: [...HOME_ROW, "e", "i", "r", "u", "t", "z"],
    drills: [
      { type: "keys", content: "t z t z z t t z t z z t" },
      { type: "words", content: "zeit satz zug gut tag ist jetzt ziege" },
      { type: "words", content: "die zeit ist da der tag ist gut es geht zuletzt" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 9,
    phase: 2,
    newKeys: ["w", "o", "q", "p", "ü"],
    allKeys: [...HOME_ROW, ...TOP_ROW],
    drills: [
      { type: "keys", content: "w o w o q p q p ü w o ü" },
      { type: "words", content: "wo wer wort oder ort quer quelle früh würde" },
      { type: "words", content: "das wetter wird gut wo ist der ort die suppe ist da" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 10,
    phase: 2,
    newKeys: [],
    allKeys: [...HOME_ROW, ...TOP_ROW],
    drills: [
      { type: "words", content: "quote quelle prüfe würde wetter gruppe zuletzt" },
      { type: "words", content: "die zeit steht still der satz sitzt gut" },
      { type: "words", content: "du tippst jetzt weiter erst ruhig zuletzt zügig" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  // === Phase 3: Untere Reihe ===
  {
    id: 11,
    phase: 3,
    newKeys: ["n", "m"],
    allKeys: [...HOME_ROW, ...TOP_ROW, "n", "m"],
    drills: [
      { type: "keys", content: "n m n m m n n m n m m n" },
      { type: "words", content: "und nein mann name immer nehmen morgen" },
      { type: "words", content: "wir nehmen uns zeit morgen wird alles gut" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 12,
    phase: 3,
    newKeys: ["b", "c", "v", ",", "."],
    allKeys: [...HOME_ROW, ...TOP_ROW, "n", "m", "b", "c", "v", ",", "."],
    drills: [
      { type: "keys", content: "b c v b c v , . , . v b" },
      { type: "words", content: "buch brief auch noch viel voll besuch vogel" },
      { type: "sentences", content: "wir machen das jetzt. viel besser, danke." },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 13,
    phase: 3,
    newKeys: ["y", "x", "ä", "-"],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "keys", content: "y x y x ä - ä - x y ä -" },
      { type: "words", content: "wäre hätte männer gespräch extra taxi system" },
      { type: "sentences", content: "die e-mail kam gestern an. das system läuft ähnlich gut." },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  // === Phase 4: Häufige Wörter ===
  {
    id: 14,
    phase: 4,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "words", content: "der die das und ist in den von zu mit sich auf für" },
      { type: "words", content: "nicht ein eine als auch es an werden aus er hat dass" },
      { type: "words", content: "sie nach wird bei einer um am sind noch wie einem über" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 15,
    phase: 4,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "words", content: "einen so zum war haben nur oder aber vor zur bis mehr" },
      { type: "words", content: "durch man sein wurde ihr ihre ihm ihn wir uns euch" },
      { type: "words", content: "kann könnte sollte müssen dürfen wollen mögen lassen gehen" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 16,
    phase: 4,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "words", content: "öffnen zumachen beginnen starten klären bauen lösen planen" },
      { type: "words", content: "fenster problem knopf nummer projekt beispiel bericht" },
      { type: "words", content: "computer software tastatur bildschirm anzeige einstellungen" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  // === Phase 5: Großschreibung ===
  {
    id: 17,
    phase: 5,
    newKeys: ["Shift"],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "words", content: "Der Die Das Und Ist Für Auch Kann War Wir Sie Er" },
      { type: "words", content: "Montag Dienstag Mittwoch Donnerstag Freitag Samstag Sonntag" },
      { type: "sentences", content: "Der Tag beginnt. Die Arbeit wartet. Ein Satz nach dem anderen." },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 18,
    phase: 5,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "Berlin ist die Hauptstadt von Deutschland. Wien liegt in Österreich." },
      { type: "sentences", content: "Anna schreibt ihre Mails am Morgen. Jonas liest den Bericht." },
      { type: "sentences", content: "Am Montag starten wir das Projekt. Bis Freitag ist es fertig." },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  // === Phase 6: Satzzeichen ===
  {
    id: 19,
    phase: 6,
    newKeys: ["?", "!"],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "Ist das richtig? Ja, es funktioniert. Das ist stark!" },
      { type: "sentences", content: "Moment, was? Bist du sicher? Ja! Ich sehe nach." },
      { type: "sentences", content: "Hallo zusammen. Wie geht es euch? Mir geht es gut, danke!" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 20,
    phase: 6,
    newKeys: ["'", "\"", ":", "ß"],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "Wie geht's? Mach's gut. Das war's für heute." },
      { type: "sentences", content: "Sie sagte: \"Hallo.\" Er antwortete: \"Guten Morgen.\"" },
      { type: "sentences", content: "Die Straße ist ruhig. Der Gruß kommt von Herzen. Das Maß ist voll." },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 21,
    phase: 6,
    newKeys: ["(", ")", "@", "&"],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "Schick es an name@email.de zur Durchsicht." },
      { type: "sentences", content: "Das Ergebnis (siehe unten) ist klar & richtig." },
      { type: "sentences", content: "Ruf uns an (Montag bis Freitag) oder schreib an info@firma.de." },
    ],
    completionThreshold: 92,
    isFree: false,
  },
  // === Phase 7: Sätze + Absätze ===
  {
    id: 22,
    phase: 7,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "Der beste Weg zu lernen ist tägliches Üben." },
      { type: "sentences", content: "Ein klarer Kopf und ruhige Finger machen schnelles Tippen." },
      { type: "sentences", content: "Erst kommt die Genauigkeit. Die Geschwindigkeit folgt von selbst." },
    ],
    completionThreshold: 92,
    isFree: false,
  },
  {
    id: 23,
    phase: 7,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "Gutes Schreiben beginnt mit sicherem Tippen. Wenn die Finger ohne Nachdenken laufen, bleibt der Kopf bei der Botschaft." },
      { type: "sentences", content: "Der Unterschied zwischen schnellen und langsamen Tippern ist kein Talent. Es sind tausende kleine, richtige Wiederholungen." },
      { type: "sentences", content: "Jede E-Mail, jede Nachricht, jedes Dokument baut deine Geschwindigkeit weiter auf. Tippen ist eine tägliche Fähigkeit." },
    ],
    completionThreshold: 92,
    isFree: false,
  },
  {
    id: 24,
    phase: 7,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "Notizen vom Meeting: Wir haben den neuen Zeitplan besprochen. Die Frist ist im März. Alle sind mit dem Vorgehen einverstanden. Die Aufgaben wurden im Team verteilt." },
      { type: "sentences", content: "Liebes Team, bitte lest das angehängte Dokument vor unserem Termin am Donnerstag. Meldet euch bei Fragen gern direkt bei mir. Ich freue mich auf euer Feedback." },
      { type: "sentences", content: "Der Quartalsbericht zeigt starkes Wachstum in allen Bereichen. Der Umsatz stieg um zwölf Prozent im Vergleich zum Vorjahr. Die Kundenzufriedenheit bleibt in allen Regionen hoch." },
    ],
    completionThreshold: 92,
    isFree: false,
  },
  // === Phase 8: Geschwindigkeit ===
  {
    id: 25,
    phase: 8,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "words", content: "der die und in den von zu das mit sich des auf für ist im" },
      { type: "words", content: "dem nicht ein eine als auch es an werden aus er hat dass sie" },
      { type: "words", content: "nach wird bei einer um am sind noch wie einem über einen so" },
    ],
    completionThreshold: 92,
    isFree: false,
  },
  {
    id: 26,
    phase: 8,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "Geschwindigkeit kommt aus dem Muskelgedächtnis, nicht aus mehr Anstrengung. Entspann die Hände und lass die Finger arbeiten." },
      { type: "sentences", content: "Franz jagt im komplett verwahrlosten Taxi quer durch Bayern. Zwölf Boxkämpfer jagen Viktor quer über den großen Sylter Deich." },
      { type: "sentences", content: "Tippen ist wie Radfahren. Einmal richtig gelernt, verlernst du es nie. Die Fähigkeit bleibt ein Leben lang." },
    ],
    completionThreshold: 94,
    isFree: false,
  },
  {
    id: 27,
    phase: 8,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "Eine gut geschriebene E-Mail spart allen Zeit. Klares Schreiben beginnt mit sicherem Tippen. Wer schnell tippt, denkt freier." },
      { type: "sentences", content: "Der letzte Test: Tippe diesen Absatz so schnell und so genau du kannst. Schau nicht auf die Tastatur. Vertrau deinen Fingern." },
      { type: "sentences", content: "Du hast jede Lektion dieses Kurses abgeschlossen. Deine Finger arbeiten jetzt mit System. Das ist dein neuer Standard. Geh und schreib etwas Großartiges." },
    ],
    completionThreshold: 94,
    isFree: false,
  },
];

export const meta: Record<number, LessonMeta> = {
  0: {
    title: "Finde die Markierungen",
    subtitle: "Schau auf deine Tastatur: Auf den Tasten F und J sind kleine Noppen. Lege deine Zeigefinger darauf - links auf F, rechts auf J. Von dieser Position aus erreichst du alle anderen Tasten.",
    newKeysLabel: "F und J",
    completionMessage: "Gut. Deine Finger wissen jetzt, wo sie hingehören.",
    insight: "Die Noppen auf F und J gibt es auf fast jeder Tastatur der Welt - damit deine Finger ohne Hinsehen zurück in die Ausgangsposition finden. Blind orientieren ist das Grundprinzip des ganzen Systems.",
  },
  1: {
    title: "F und J - Deine Anker",
    subtitle: "Die beiden wichtigsten Tasten. Von hier aus erreichst du alles.",
    newKeysLabel: "F und J",
    completionMessage: "Solide Basis. Weiter geht's.",
    insight: "Nicht dein Bewusstsein lernt tippen, sondern dein Kleinhirn. Es baut aus jeder korrekten Wiederholung eine Bewegungsbahn. Deshalb gilt: bewusst langsam jetzt, unbewusst schnell später.",
  },
  2: {
    title: "D und K dazu",
    subtitle: "Mittelfinger links auf D, Mittelfinger rechts auf K.",
    newKeysLabel: "D und K",
    completionMessage: "Vier Finger arbeiten schon. Läuft.",
    insight: "Warum so viel Wiederholung? Myelin. Bei jeder Wiederholung isoliert dein Körper die genutzte Nervenbahn stärker - das Signal wird messbar schneller. Üben ist wörtlich Leitungsausbau.",
  },
  3: {
    title: "S und L dazu",
    subtitle: "Ringfinger links auf S, Ringfinger rechts auf L.",
    newKeysLabel: "S und L",
    completionMessage: "Sechs Finger im Einsatz. Die Grundreihe wächst.",
    insight: "Genauigkeit vor Tempo - das ist keine Floskel. Fehler trainieren sich genauso ein wie Treffer. Wer schnell und falsch übt, automatisiert die Fehler gleich mit.",
  },
  4: {
    title: "A und Ö dazu",
    subtitle: "Kleiner Finger links auf A, kleiner Finger rechts auf Ö.",
    newKeysLabel: "A und Ö",
    completionMessage: "Die kleinen Finger sind dabei - und du tippst schon echte Wörter.",
    insight: "Die kleinen Finger fühlen sich wackelig an? Völlig normal. Sie bekommen im Alltag am wenigsten Feinmotorik-Training von allen Fingern. Das gibt sich schneller, als du denkst.",
  },
  5: {
    title: "G und H - die Mitte",
    subtitle: "Beide Zeigefinger strecken sich zur Mitte. Damit ist die Grundreihe komplett.",
    newKeysLabel: "G und H",
    completionMessage: "Grundreihe gemeistert. Das ist die Basis für alles Weitere.",
    insight: "Die Grundreihe heißt auf Englisch \"home row\" - Zuhause. Profis kehren nach jedem einzelnen Anschlag dorthin zurück. Genau deshalb erreichen sie jede Taste in einem einzigen Zug.",
  },
  6: {
    title: "E und I - die Vieltipper",
    subtitle: "Zeigefinger und Mittelfinger greifen nach oben.",
    newKeysLabel: "E und I",
    completionMessage: "Zwei der häufigsten Buchstaben. Stark.",
    insight: "Das E ist mit Abstand der häufigste Buchstabe im Deutschen - rund 17 Prozent aller Buchstaben. Ab dieser Lektion tippst du echte Wörter, und dein Gehirn beginnt, in Mustern statt in Einzeltasten zu denken.",
  },
  7: {
    title: "R und U dazu",
    subtitle: "Die Zeigefinger übernehmen die obere Reihe.",
    newKeysLabel: "R und U",
    completionMessage: "Dein Wortschatz wächst mit jeder Lektion.",
    insight: "Chunking: Dein Gehirn fasst Buchstabenfolgen zu Einheiten zusammen. Bald tippst du \"der\" nicht mehr als d-e-r, sondern als eine einzige Bewegung. So entsteht Tempo.",
  },
  8: {
    title: "T und Z dazu",
    subtitle: "Zwei starke deutsche Buchstaben - jetzt werden ganze Sätze möglich.",
    newKeysLabel: "T und Z",
    completionMessage: "Jetzt kannst du erste richtige Sätze tippen.",
    insight: "Wenn es sich heute zäher anfühlt als gestern: gut so. Dein Gehirn festigt Gelerntes im Hintergrund, vor allem im Schlaf. Ein Plateau ist kein Stillstand, sondern Konsolidierung.",
  },
  9: {
    title: "W, O, Q, P und Ü",
    subtitle: "Der Rest der oberen Reihe in einem Zug.",
    newKeysLabel: "W, O, Q, P, Ü",
    completionMessage: "Obere Reihe komplett. Zwei Drittel der Tastatur gehören dir.",
    insight: "15 Minuten täglich schlagen 2 Stunden am Sonntag - deutlich. Der Grund heißt Spacing-Effekt: Die Nächte zwischen den Einheiten festigen das Gelernte. Dein Schlaf trainiert mit.",
  },
  10: {
    title: "Obere Reihe festigen",
    subtitle: "Grundreihe plus obere Reihe. Fließende Wortfolgen.",
    newKeysLabel: "Wiederholung",
    completionMessage: "Sicher in zwei Reihen. Die Untere wartet schon.",
    insight: "Der wichtigste Moment des Kurses: Widersteh dem Blick auf die Tastatur. Jeder Blick unterbricht den Aufbau der blinden Zuordnung - und genau die ist das Ziel.",
  },
  11: {
    title: "N und M dazu",
    subtitle: "Die Zeigefinger greifen nach unten.",
    newKeysLabel: "N und M",
    completionMessage: "N und M sitzen. Deutsche Texte öffnen sich.",
    insight: "Nach dem E ist das N der zweithäufigste Buchstabe im Deutschen. Mit dieser Lektion kannst du rund 80 Prozent aller deutschen Alltagstexte tippen.",
  },
  12: {
    title: "B, C, V und Satzzeichen",
    subtitle: "Komma und Punkt - deine Sätze bekommen Struktur.",
    newKeysLabel: "B, C, V, Komma, Punkt",
    completionMessage: "Jetzt kannst du komplette Sätze mit Satzzeichen tippen.",
    insight: "Fehler bemerken ist Lernen: In dem Moment, in dem du merkst, dass der Finger falsch lag, aktualisiert dein Gehirn seine Karte. Deshalb bringt bewusstes Korrigieren mehr als stures Weitertippen.",
  },
  13: {
    title: "Y, X und das Ä",
    subtitle: "Die letzten Buchstaben - inklusive Umlaut mit dem kleinen Finger.",
    newKeysLabel: "Y, X, Ä, Bindestrich",
    completionMessage: "Alle Buchstaben gelernt. Jedes deutsche Wort ist jetzt möglich.",
    insight: "Umlaute blind zu treffen ist die Königsdisziplin auf QWERTZ - die meisten Selbstlerner schaffen es nie. Ab heute gehörst du zur Minderheit, die es kann.",
  },
  14: {
    title: "Die häufigsten Wörter",
    subtitle: "Die Wörter, die du am meisten tippst. Schnell und sicher.",
    newKeysLabel: "Häufige Wörter",
    completionMessage: "Diese Wörter sitzen. Deine Alltagstexte werden schneller.",
    insight: "Die 100 häufigsten Wörter machen etwa die Hälfte jedes deutschen Textes aus. Wer genau diese Wörter automatisiert, macht den größten Tempo-Sprung des ganzen Kurses.",
  },
  15: {
    title: "Noch mehr Alltagswörter",
    subtitle: "Verben, Pronomen, Verbindungswörter - der Kitt jedes Satzes.",
    newKeysLabel: "Häufige Wörter",
    completionMessage: "Der Grundwortschatz fließt.",
    insight: "Automatisierung heißt: Dein Gehirn prüft nicht mehr jeden Buchstaben, sondern feuert die ganze Sequenz auf einmal ab. Genau das passiert gerade mit diesen Wörtern.",
  },
  16: {
    title: "Büro-Vokabular",
    subtitle: "Die Wörter aus deinem Arbeitsalltag.",
    newKeysLabel: "Alltagswörter",
    completionMessage: "Dein Arbeitswortschatz sitzt.",
    insight: "Transfer-Effekt: Was du hier übst, sind exakt die Wörter aus deinen echten E-Mails und Dokumenten. Ab jetzt zahlt jede Übungsminute direkt auf deinen Arbeitstag ein.",
  },
  17: {
    title: "Großschreibung mit Shift",
    subtitle: "Die Umschalttaste - immer mit der Gegenhand.",
    newKeysLabel: "Shift",
    completionMessage: "Großbuchstaben sitzen. Sätze sehen jetzt richtig aus.",
    insight: "Die Profi-Regel für Shift: immer die Gegenhand. Großes A? Rechter kleiner Finger hält Shift, links tippt das A. So bleibt keine Hand blockiert.",
  },
  18: {
    title: "Sätze mit Großschreibung",
    subtitle: "Namen, Satzanfänge, Substantive - wie im echten Text.",
    newKeysLabel: "Wiederholung",
    completionMessage: "Großschreibung läuft nebenbei. So soll es sein.",
    insight: "Deutsch schreibt alle Substantive groß - dein Shift-Training läuft hier automatisch doppelt so intensiv wie bei englischen Texten. Ein versteckter Vorteil des deutschen Kurses.",
  },
  19: {
    title: "Frage und Ausruf",
    subtitle: "Fragezeichen und Ausrufezeichen im Satzfluss.",
    newKeysLabel: "? und !",
    completionMessage: "Deine Sätze haben jetzt Stimme.",
    insight: "Flüssiges Schreiben heißt: kein Stocken vor Satzzeichen. Die Mini-Pause vor dem Punkt kostet Ungeübte bei jedem Satz Zeit - Profis tippen durch. Bald du auch.",
  },
  20: {
    title: "Apostroph, Anführungszeichen und ß",
    subtitle: "Die Feinheiten deutscher Texte - inklusive Eszett.",
    newKeysLabel: "' \" : ß",
    completionMessage: "Straße, Gruß, Maß - das ß gehorcht dir jetzt.",
    insight: "Das ß liegt rechts neben der Null - kaum jemand trifft es blind. Fun Fact: Die Schweiz hat es komplett abgeschafft und schreibt immer ss. In Deutschland und Österreich bleibt es Pflicht.",
  },
  21: {
    title: "Klammern, @ und Co",
    subtitle: "Sonderzeichen für E-Mails und technische Texte.",
    newKeysLabel: "( ) @ &",
    completionMessage: "E-Mail-Adressen tippst du jetzt blind.",
    insight: "Das @-Zeichen und die Klammern sind die Bürotasten schlechthin. Wer sie blind trifft, schreibt E-Mail-Adressen und Verweise, ohne den Lesefluss zu verlieren.",
  },
  22: {
    title: "Fließende Sätze",
    subtitle: "Ganze Gedanken am Stück, Satz für Satz.",
    newKeysLabel: "Sätze",
    completionMessage: "Sätze fließen. Absätze sind der nächste Schritt.",
    insight: "Wann kannst du \"frei schreiben\"? Faustregel: Wenn deine Genauigkeit bei vollem Alphabet über 95 Prozent liegt, denkst du in Sätzen statt in Tasten. Du bist näher dran, als du glaubst.",
  },
  23: {
    title: "Längere Absätze",
    subtitle: "Konzentration über mehrere Sätze halten.",
    newKeysLabel: "Absätze",
    completionMessage: "Du hältst die Konzentration über längere Texte.",
    insight: "Ausdauer ist eine eigene Fähigkeit. Kurze Drills trainieren Präzision, lange Absätze trainieren das Durchhalten - beides zusammen macht Alltagstauglichkeit.",
  },
  24: {
    title: "Echte Arbeitstexte",
    subtitle: "Meeting-Notizen, Team-Mails, Berichte - dein Alltag als Übung.",
    newKeysLabel: "Praxistexte",
    completionMessage: "Das war kein Übungstext mehr. Das war Arbeit - und sie lief.",
    insight: "Echte Arbeitstexte enthalten Zahlen, Namen, Doppelpunkte und Kommas an unbequemen Stellen. Genau deshalb übst du sie hier - dein Training wird deckungsgleich mit deinem Alltag.",
  },
  25: {
    title: "Tempo-Runden",
    subtitle: "Die häufigsten Wörter, so schnell du kannst.",
    newKeysLabel: "Tempo",
    completionMessage: "Das war schnell. Und es wird noch schneller.",
    insight: "Jetzt darfst du loslassen: Bei über 95 Prozent Genauigkeit ist bewusstes Beschleunigen dran. Wenn die Fehlerquote kurz steigt, ist das Teil des Plans - sie pendelt sich höher wieder ein.",
  },
  26: {
    title: "Pangramme",
    subtitle: "Sätze mit allen Buchstaben des Alphabets.",
    newKeysLabel: "Alle Tasten",
    completionMessage: "Alle 30 Buchstaben in Bewegung. Beeindruckend.",
    insight: "Pangramme enthalten jeden Buchstaben des Alphabets mindestens einmal - das Ganzkörpertraining fürs Tippen. \"Franz jagt im komplett verwahrlosten Taxi quer durch Bayern\" ist der deutsche Klassiker.",
  },
  27: {
    title: "Der letzte Schliff",
    subtitle: "Volle Geschwindigkeit, volle Genauigkeit. Zeig, was du kannst.",
    newKeysLabel: "Abschluss",
    completionMessage: "Kurs abgeschlossen. Deine Finger arbeiten jetzt mit System.",
    insight: "Fertig heißt: Die Automatisierung steht. Ab jetzt ist jede E-Mail Training - deine Kurve steigt noch Monate weiter, ganz ohne Übungsplan. Genau so soll es sein.",
  },
};
