import type { Lesson, LessonMeta } from "./types";

// English QWERTY curriculum.
// Every drill uses ONLY keys unlocked up to that lesson
// (this fixed two legacy bugs: words containing "a" before lesson 4,
// and g/h appearing in texts without ever being taught).

const HOME_ROW = ["a", "s", "d", "f", "g", "h", "j", "k", "l", ";", " "];
const TOP_ROW = ["q", "w", "e", "r", "t", "y", "u", "i", "o", "p"];
const BOTTOM_ROW = ["z", "x", "c", "v", "b", "n", "m", ",", ".", "/"];
const ALL_LETTERS = [...HOME_ROW, ...TOP_ROW, ...BOTTOM_ROW];

export const lessons: Lesson[] = [
  // === Phase 0: Introduction ===
  {
    id: 0,
    phase: 0,
    newKeys: ["f", "j"],
    allKeys: ["f", "j", " "],
    drills: [
      { type: "keys", content: "f j f j f j j f j f f j" },
      { type: "keys", content: "ff jj fj jf ff jj fj jf" },
      { type: "keys", content: "fjf jfj fjf jfj fjf jfj" },
    ],
    completionThreshold: 90,
    isFree: true,
  },
  // === Phase 1: Home Row ===
  {
    id: 1,
    phase: 1,
    newKeys: ["f", "j"],
    allKeys: ["f", "j", " "],
    drills: [
      { type: "keys", content: "f j f j j f f j j f j f f j" },
      { type: "keys", content: "ff jj ff jj fj fj jf jf fjf jfj" },
      { type: "keys", content: "fj jf ffj jjf fjj jff fjfj jfjf" },
    ],
    completionThreshold: 90,
    isFree: true,
  },
  {
    id: 2,
    phase: 1,
    newKeys: ["d", "k"],
    allKeys: ["f", "j", "d", "k", " "],
    drills: [
      { type: "keys", content: "d k d k k d d k k d d k" },
      { type: "keys", content: "fd jk df kj fdk jkf dkf" },
      { type: "keys", content: "dd kk dk kd fdk kjf dkfj" },
    ],
    completionThreshold: 90,
    isFree: true,
  },
  {
    id: 3,
    phase: 1,
    newKeys: ["s", "l"],
    allKeys: ["f", "j", "d", "k", "s", "l", " "],
    drills: [
      { type: "keys", content: "s l s l l s s l l s s l" },
      { type: "keys", content: "sd lk fs jl ds kl fds jkl" },
      { type: "keys", content: "sl ls ssl lls fsl jkl dsl skl" },
    ],
    completionThreshold: 90,
    isFree: true,
  },
  {
    id: 4,
    phase: 1,
    newKeys: ["a", ";"],
    allKeys: ["a", "s", "d", "f", "j", "k", "l", ";", " "],
    drills: [
      { type: "keys", content: "a ; a ; ; a a ; a ; ; a" },
      { type: "keys", content: "as ;l df jk sa l; fd kj" },
      { type: "words", content: "a sad lad asks a lass; a fall" },
    ],
    completionThreshold: 90,
    isFree: true,
  },
  {
    id: 5,
    phase: 1,
    newKeys: ["g", "h"],
    allKeys: [...HOME_ROW],
    drills: [
      { type: "keys", content: "g h g h h g g h g h h g" },
      { type: "words", content: "gas has had gal glad sash flag shall glass" },
      { type: "sentences", content: "a glad lad has a glass; dad shall ask" },
    ],
    completionThreshold: 90,
    isFree: true,
  },
  // === Phase 2: Top Row ===
  {
    id: 6,
    phase: 2,
    newKeys: ["e", "i"],
    allKeys: [...HOME_ROW, "e", "i"],
    drills: [
      { type: "keys", content: "e i e i i e e i i e e i" },
      { type: "keys", content: "de ki ed ik fed kid dei" },
      { type: "words", content: "die side like file idea slide" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 7,
    phase: 2,
    newKeys: ["r", "u"],
    allKeys: [...HOME_ROW, "e", "i", "r", "u"],
    drills: [
      { type: "keys", content: "r u r u u r r u u r r u" },
      { type: "keys", content: "fr ju rf uj fur rue ruf" },
      { type: "words", content: "rule fire sure ride user" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 8,
    phase: 2,
    newKeys: ["w", "o"],
    allKeys: [...HOME_ROW, "e", "i", "r", "u", "w", "o"],
    drills: [
      { type: "keys", content: "w o w o o w w o o w w o" },
      { type: "keys", content: "sw ol ws lo ow wo wok owl" },
      { type: "words", content: "slow work world flower would" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 9,
    phase: 2,
    newKeys: ["q", "p", "t", "y"],
    allKeys: [...HOME_ROW, ...TOP_ROW],
    drills: [
      { type: "keys", content: "q p t y q p t y p q y t" },
      { type: "words", content: "type quite past your pretty" },
      { type: "sentences", content: "you type quite fast; pretty solid work" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 10,
    phase: 2,
    newKeys: [],
    allKeys: [...HOME_ROW, ...TOP_ROW],
    drills: [
      { type: "words", content: "require deploy quite opposite forward" },
      { type: "sentences", content: "your words flow like water; type with purpose" },
      { type: "sentences", content: "keep your eyes off the keys; trust your fingers" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  // === Phase 3: Bottom Row ===
  {
    id: 11,
    phase: 3,
    newKeys: ["n", "m", "v", "b"],
    allKeys: [...HOME_ROW, ...TOP_ROW, "n", "m", "v", "b"],
    drills: [
      { type: "keys", content: "n m v b n m v b m n b v" },
      { type: "words", content: "number move every been name" },
      { type: "sentences", content: "every number moves forward; never stop" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 12,
    phase: 3,
    newKeys: ["c", ",", "x", "."],
    allKeys: [...HOME_ROW, ...TOP_ROW, "n", "m", "v", "b", "c", ",", "x", "."],
    drills: [
      { type: "keys", content: "c , x . c , x . , c . x" },
      { type: "words", content: "next, expect. complex, mix." },
      { type: "sentences", content: "excellent work, next comes more. expect quick results." },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 13,
    phase: 3,
    newKeys: ["z", "/"],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "keys", content: "z / z / / z z / z / / z" },
      { type: "words", content: "zone zero fizz buzz quiz jazz" },
      { type: "sentences", content: "the quick brown fox jumps over the lazy dog." },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  // === Phase 4: Common Words ===
  {
    id: 14,
    phase: 4,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "words", content: "the and for are but not you all can her was one our" },
      { type: "words", content: "have from this will your been each make like long" },
      { type: "words", content: "time very when come could people than first water been" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 15,
    phase: 4,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "words", content: "about their which would there other into more some" },
      { type: "words", content: "after also back because before between both came" },
      { type: "words", content: "should still through under where while work three" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 16,
    phase: 4,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "words", content: "open close begin start focus clear build solve plan" },
      { type: "words", content: "window problem button review number project example" },
      { type: "words", content: "computer software keyboard monitor display settings" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  // === Phase 5: Capitalization ===
  {
    id: 17,
    phase: 5,
    newKeys: ["Shift"],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "words", content: "The And For Are But Not You All Can Her Was One" },
      { type: "words", content: "Monday Tuesday Wednesday Thursday Friday Saturday Sunday" },
      { type: "sentences", content: "The quick fox jumps. A red car drives fast. My dog runs." },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 18,
    phase: 5,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "Berlin is the capital of Germany. Paris is in France." },
      { type: "sentences", content: "Sarah likes to code in Python. Tom prefers JavaScript." },
      { type: "sentences", content: "On Monday we start the project. By Friday it ships." },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  // === Phase 6: Punctuation ===
  {
    id: 19,
    phase: 6,
    newKeys: [".", ",", "?", "!"],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "Is this correct? Yes, it works. That is great!" },
      { type: "sentences", content: "Wait, what? Are you sure? Yes! Let me check." },
      { type: "sentences", content: "Hello, world. How are you? I am fine, thanks!" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 20,
    phase: 6,
    newKeys: ["'", "\"", "-", ":"],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "It's a good day. Don't stop now. I can't wait." },
      { type: "sentences", content: "She said: \"Hello.\" He replied: \"Hi there.\"" },
      { type: "sentences", content: "The well-known fact: practice makes perfect." },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 21,
    phase: 6,
    newKeys: ["(", ")", "@", "&"],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "Send it to name@email.com for review." },
      { type: "sentences", content: "The result (see below) is clear & correct." },
      { type: "sentences", content: "Call us at (555) 123-4567 or email info@company.com." },
    ],
    completionThreshold: 92,
    isFree: false,
  },
  // === Phase 7: Sentences + Paragraphs ===
  {
    id: 22,
    phase: 7,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "The best way to learn is to practice every day." },
      { type: "sentences", content: "A clear mind and steady fingers make fast typing." },
      { type: "sentences", content: "Focus on accuracy first. Speed follows naturally." },
    ],
    completionThreshold: 92,
    isFree: false,
  },
  {
    id: 23,
    phase: 7,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "Good writing starts with confident typing. When your fingers move without thinking, your mind stays on the message." },
      { type: "sentences", content: "The difference between a fast typist and a slow one is not talent. It is thousands of small, correct repetitions." },
      { type: "sentences", content: "Every email you write, every message you send, every document you draft builds your speed. Typing is a daily skill." },
    ],
    completionThreshold: 92,
    isFree: false,
  },
  {
    id: 24,
    phase: 7,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "Meeting notes from today: We discussed the new project timeline. The deadline is set for March. Everyone agreed on the approach. Action items were assigned to each team member." },
      { type: "sentences", content: "Dear team, please review the attached document before our meeting on Thursday. Let me know if you have any questions or concerns. Looking forward to your feedback." },
      { type: "sentences", content: "The quarterly report shows strong growth in all areas. Revenue increased by twelve percent compared to last year. Customer satisfaction scores remain high across all regions." },
    ],
    completionThreshold: 92,
    isFree: false,
  },
  // === Phase 8: Speed + Fluency ===
  {
    id: 25,
    phase: 8,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "words", content: "the of and to in is it you that he was for on are with" },
      { type: "words", content: "as his they be at one have this from or had by not but" },
      { type: "words", content: "some what there we can out other were all your when up" },
    ],
    completionThreshold: 92,
    isFree: false,
  },
  {
    id: 26,
    phase: 8,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "Speed comes from muscle memory, not from trying harder. Relax your hands and let your fingers do the work." },
      { type: "sentences", content: "The quick brown fox jumps over the lazy dog. Pack my box with five dozen liquor jugs." },
      { type: "sentences", content: "Typing is like riding a bike. Once you learn it properly, you never forget. The skill stays with you for life." },
    ],
    completionThreshold: 94,
    isFree: false,
  },
  {
    id: 27,
    phase: 8,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "A well-written email saves time for everyone. Clear writing starts with confident typing. When you type fast, you think fast." },
      { type: "sentences", content: "The final test: type this paragraph as fast and as accurately as you can. Do not look at the keyboard. Trust your fingers." },
      { type: "sentences", content: "You have completed every lesson in this course. Your fingers move with purpose now. This is your new normal. Go type something great." },
    ],
    completionThreshold: 94,
    isFree: false,
  },
];

export const meta: Record<number, LessonMeta> = {
  0: {
    title: "Find the Bumps",
    subtitle: "Look at your keyboard: the F and J keys have small bumps on them. Place your index fingers there - left on F, right on J. This is your home position for reaching every other key.",
    newKeysLabel: "F and J",
    completionMessage: "Good. Your fingers know where they belong now.",
    insight: "The bumps on F and J exist on nearly every keyboard in the world - so your fingers can find home without looking. Orienting blind is the core principle behind the whole system.",
  },
  1: {
    title: "F and J - Your Anchors",
    subtitle: "The two most important keys. Everything starts here.",
    newKeysLabel: "F and J",
    completionMessage: "Solid foundation. Let's keep going.",
    insight: "It's not your conscious mind that learns to type - it's your cerebellum. Every correct repetition builds a motor pathway. That's why the rule is: deliberately slow now, automatically fast later.",
  },
  2: {
    title: "Adding D and K",
    subtitle: "Middle finger left on D, middle finger right on K.",
    newKeysLabel: "D and K",
    completionMessage: "Four fingers working already. Nice.",
    insight: "Why so much repetition? Myelin. Each rep insulates the nerve pathway you just used, making the signal measurably faster. Practice is literally upgrading your wiring.",
  },
  3: {
    title: "Adding S and L",
    subtitle: "Ring finger left on S, ring finger right on L.",
    newKeysLabel: "S and L",
    completionMessage: "Six fingers active. You're building real muscle memory.",
    insight: "Accuracy before speed is not a slogan. Mistakes train in exactly like successes do. Practice fast and sloppy, and you automate the sloppiness along with it.",
  },
  4: {
    title: "Adding A and ;",
    subtitle: "Pinky finger left on A, pinky finger right on ;",
    newKeysLabel: "A and ;",
    completionMessage: "The full stretch. Both pinkies are in the game.",
    insight: "Pinkies feel wobbly? Completely normal. They get the least fine-motor training of all your fingers in daily life. It passes faster than you think.",
  },
  5: {
    title: "G and H - the Middle",
    subtitle: "Both index fingers stretch to the center. The home row is complete.",
    newKeysLabel: "G and H",
    completionMessage: "Home row mastered. This is the foundation for everything else.",
    insight: "The home row is called home for a reason: pros return there after every single keystroke. That's exactly why they can reach any key in one move.",
  },
  6: {
    title: "E and I - Reaching Up",
    subtitle: "Middle fingers up to the top row. E left, I right.",
    newKeysLabel: "E and I",
    completionMessage: "Two of the most common letters. Strong progress.",
    insight: "E is by far the most common letter in English - about one in eight letters. From this lesson on, you type real words, and your brain starts thinking in patterns instead of single keys.",
  },
  7: {
    title: "Adding R and U",
    subtitle: "Index fingers up. R left, U right.",
    newKeysLabel: "R and U",
    completionMessage: "Your vocabulary grows with every lesson.",
    insight: "Chunking: your brain bundles letter sequences into units. Soon you'll type \"the\" not as t-h-e but as one single motion. That's where speed comes from.",
  },
  8: {
    title: "Adding W and O",
    subtitle: "Ring fingers up. W left, O right.",
    newKeysLabel: "W and O",
    completionMessage: "The top row is taking shape.",
    insight: "If today feels harder than yesterday: good sign. Your brain consolidates skills in the background, mostly during sleep. A plateau is not a standstill - it's construction work.",
  },
  9: {
    title: "Q, P, T and Y",
    subtitle: "The remaining top row keys.",
    newKeysLabel: "Q, P, T, Y",
    completionMessage: "Top row complete. Two rows mastered.",
    insight: "15 minutes daily beats 2 hours on Sunday - by a lot. The reason is the spacing effect: the nights between sessions lock in what you learned. Your sleep trains with you.",
  },
  10: {
    title: "Top Row Complete",
    subtitle: "Home row plus top row. Flowing sentences.",
    newKeysLabel: "Review",
    completionMessage: "Two rows down. One more to go.",
    insight: "The most important moment of the course: resist looking at the keyboard. Every glance interrupts the blind mapping your brain is building - and that mapping is the entire goal.",
  },
  11: {
    title: "N, M, V and B",
    subtitle: "The most common bottom row keys first.",
    newKeysLabel: "N, M, V, B",
    completionMessage: "The bottom row begins. Almost the full alphabet.",
    insight: "N is one of the top three letters in English. With this lesson you can type roughly 80 percent of everyday English text.",
  },
  12: {
    title: "C, Comma, X and Period",
    subtitle: "Punctuation and less common letters.",
    newKeysLabel: "C, X and punctuation",
    completionMessage: "Now you can type complete sentences with punctuation.",
    insight: "Noticing a mistake IS learning: the moment you feel the wrong finger move, your brain updates its map. Conscious correction beats powering through.",
  },
  13: {
    title: "Z and /",
    subtitle: "The last keys. After this, you have the full alphabet.",
    newKeysLabel: "Z and /",
    completionMessage: "Every key learned. Every word is now possible.",
    insight: "Z is the rarest letter in English - and that's exactly why untrained typists never learn it blind. You just did. Welcome to the minority.",
  },
  14: {
    title: "100 Most Common Words",
    subtitle: "The words you type most. Fast and confident.",
    newKeysLabel: "Common words",
    completionMessage: "These words are second nature now.",
    insight: "The 100 most common words make up about half of any English text. Automating exactly these words is the single biggest speed jump in the whole course.",
  },
  15: {
    title: "Two-Syllable Words",
    subtitle: "Longer words that need to flow smoothly.",
    newKeysLabel: "Two-syllable words",
    completionMessage: "Longer words are no longer a challenge.",
    insight: "Automation means your brain stops checking every letter and fires the whole sequence at once. That is exactly what's happening to these words right now.",
  },
  16: {
    title: "Everyday Vocabulary",
    subtitle: "Words from work and tech: computer, software, project.",
    newKeysLabel: "Work + tech",
    completionMessage: "Your work vocabulary is solid. On to capitalization.",
    insight: "Transfer effect: what you practice here are the exact words from your real emails and documents. From now on, every practice minute pays directly into your workday.",
  },
  17: {
    title: "Shift Key and Capital Letters",
    subtitle: "Hold Shift with your pinky, type the letter.",
    newKeysLabel: "Shift",
    completionMessage: "Capitals mastered. Weekdays, names, sentence starts.",
    insight: "The pro rule for Shift: always the opposite hand. Capital A? Right pinky holds Shift, left hand types the A. That way neither hand ever locks up.",
  },
  18: {
    title: "Sentences with Capitals",
    subtitle: "Real sentences with proper capitalization.",
    newKeysLabel: "Review",
    completionMessage: "Capitalization is now automatic. Good.",
    insight: "Every sentence starts with a capital - so your Shift training now runs continuously without you thinking about it. The automation installs itself.",
  },
  19: {
    title: "Period, Comma, Question, Exclamation",
    subtitle: "The four most important punctuation marks.",
    newKeysLabel: ". , ? !",
    completionMessage: "Basic punctuation is solid.",
    insight: "Fluent writing means no stalling before punctuation. That micro-pause before every period costs untrained typists time on every sentence - pros type straight through. Soon you will too.",
  },
  20: {
    title: "Apostrophe, Quotes, Hyphen",
    subtitle: "Punctuation for quotes and compound words.",
    newKeysLabel: "' \" - :",
    completionMessage: "You can now type more complex texts correctly.",
    insight: "English is contraction country: it's, don't, can't, you're. The apostrophe shows up so often that hitting it blind changes your overall fluency more than you'd expect.",
  },
  21: {
    title: "Brackets, @, &",
    subtitle: "Special characters for emails and technical text.",
    newKeysLabel: "( ) @ &",
    completionMessage: "Email addresses and special characters are no problem.",
    insight: "The @ sign and brackets are the office keys par excellence. Hit them blind and you write email addresses and references without ever losing your reading flow.",
  },
  22: {
    title: "Quick Sentences",
    subtitle: "Type fluently, sentence by sentence.",
    newKeysLabel: "Sentences",
    completionMessage: "Short sentences flow. On to longer texts.",
    insight: "When can you \"write freely\"? Rule of thumb: once your accuracy stays above 95 percent across the full alphabet, you think in sentences instead of keys. You're closer than you think.",
  },
  23: {
    title: "Longer Sentences",
    subtitle: "Two to three sentences at a time. Stay focused.",
    newKeysLabel: "Longer sentences",
    completionMessage: "You hold focus over longer texts.",
    insight: "Endurance is its own skill. Short drills train precision, long paragraphs train staying power - together they make you fast in real life, not just in exercises.",
  },
  24: {
    title: "Short Paragraphs",
    subtitle: "Type full paragraphs: emails, reports, notes.",
    newKeysLabel: "Paragraphs",
    completionMessage: "You type full paragraphs fluently and correctly.",
    insight: "Real work texts have numbers, names, colons and commas in awkward places. That's exactly why you practice them here - your training becomes identical to your workday.",
  },
  25: {
    title: "Speed: Common Words",
    subtitle: "The most common words as fast as possible.",
    newKeysLabel: "Speed drill",
    completionMessage: "Your speed is climbing. Keep going.",
    insight: "Now you're allowed to let go: above 95 percent accuracy, deliberate acceleration is the program. If your error rate rises briefly, that's part of the plan - it settles back at a higher speed.",
  },
  26: {
    title: "Speed: Sentences",
    subtitle: "Type sentences at speed. Accuracy still matters.",
    newKeysLabel: "Speed drill",
    completionMessage: "Speed and accuracy in balance. Strong.",
    insight: "Pangrams contain every letter of the alphabet at least once - full-body training for typing. \"The quick brown fox jumps over the lazy dog\" is the classic for a reason.",
  },
  27: {
    title: "The Final Test",
    subtitle: "Show what you've learned. Type with confidence.",
    newKeysLabel: "All keys",
    completionMessage: "Done. You now type with all ten fingers.",
    insight: "Done means: the automation is in place. From now on every email is practice - your curve keeps climbing for months without any training plan. Exactly as designed.",
  },
};
