import type { Lesson, LessonMeta } from "./types";

// French AZERTY curriculum.
// AZERTY specifics: home row is q s d f g h j k l m (no vowels!),
// a/z sit in the top row, w/x in the bottom row, and the accented
// characters é è ç à are direct keys on the number row.
// Circumflex/diaeresis (ê î ô û ë) need a dead key - deliberately avoided.
// Every drill uses ONLY keys unlocked up to that lesson.

const HOME_ROW = ["q", "s", "d", "f", "g", "h", "j", "k", "l", "m", " "];
const TOP_ROW = ["a", "z", "e", "r", "t", "y", "u", "i", "o", "p"];
const BOTTOM_ROW = ["w", "x", "c", "v", "b", "n", ",", "."];
const ACCENTS = ["é", "è", "à", "ç"];
const ALL_LETTERS = [...HOME_ROW, ...TOP_ROW, ...BOTTOM_ROW, ...ACCENTS];

export const lessons: Lesson[] = [
  // === Phase 0: Introduction ===
  {
    id: 0,
    phase: 0,
    newKeys: ["f", "j"],
    allKeys: ["f", "j", " "],
    drills: [
      { type: "keys", content: "f j f j f j j f j f f j" },
      { type: "keys", content: "ff jj fj jf ff jj fj jf" },
      { type: "keys", content: "fjf jfj fjf jfj fjf jfj" },
    ],
    completionThreshold: 90,
    isFree: true,
  },
  // === Phase 1: Rangée de base ===
  {
    id: 1,
    phase: 1,
    newKeys: ["f", "j"],
    allKeys: ["f", "j", " "],
    drills: [
      { type: "keys", content: "f j f j j f f j j f j f f j" },
      { type: "keys", content: "ff jj ff jj fj fj jf jf fjf jfj" },
      { type: "keys", content: "fj jf ffj jjf fjj jff fjfj jfjf" },
    ],
    completionThreshold: 90,
    isFree: true,
  },
  {
    id: 2,
    phase: 1,
    newKeys: ["d", "k"],
    allKeys: ["f", "j", "d", "k", " "],
    drills: [
      { type: "keys", content: "d k d k k d d k k d d k" },
      { type: "keys", content: "fd jk df kj fdk jkf dkf" },
      { type: "keys", content: "dd kk dk kd fdk kjf dkfj" },
    ],
    completionThreshold: 90,
    isFree: true,
  },
  {
    id: 3,
    phase: 1,
    newKeys: ["s", "l"],
    allKeys: ["f", "j", "d", "k", "s", "l", " "],
    drills: [
      { type: "keys", content: "s l s l l s s l l s s l" },
      { type: "keys", content: "sd lk fs jl ds kl fds jkl" },
      { type: "keys", content: "sl ls ssl lls fsl jkl dsl skl" },
    ],
    completionThreshold: 90,
    isFree: true,
  },
  {
    id: 4,
    phase: 1,
    newKeys: ["q", "m"],
    allKeys: ["q", "s", "d", "f", "j", "k", "l", "m", " "],
    drills: [
      { type: "keys", content: "q m q m m q q m q m m q" },
      { type: "keys", content: "qs md lq mk sq ml fd jk" },
      { type: "keys", content: "qm mq qsd mlk qsdf mlkj" },
    ],
    completionThreshold: 90,
    isFree: true,
  },
  {
    id: 5,
    phase: 1,
    newKeys: ["g", "h"],
    allKeys: [...HOME_ROW],
    drills: [
      { type: "keys", content: "g h g h h g g h g h h g" },
      { type: "keys", content: "fg jh gf hj gh hg fgh jhg" },
      { type: "keys", content: "gh hg ghj fgh qsd mlk gdf hkj" },
    ],
    completionThreshold: 90,
    isFree: true,
  },
  // === Phase 2: Rangée supérieure ===
  {
    id: 6,
    phase: 2,
    newKeys: ["e", "i"],
    allKeys: [...HOME_ROW, "e", "i"],
    drills: [
      { type: "keys", content: "e i e i i e e i i e e i" },
      { type: "keys", content: "de ki ed ik fe ei je il" },
      { type: "words", content: "il elle le je me de se lis dis fille mille film" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 7,
    phase: 2,
    newKeys: ["r", "u"],
    allKeys: [...HOME_ROW, "e", "i", "r", "u"],
    drills: [
      { type: "keys", content: "r u r u u r r u u r r u" },
      { type: "keys", content: "fr ju ur ru er re rue dur" },
      { type: "words", content: "sur rue dur mur jure heure fleur mesure figure" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 8,
    phase: 2,
    newKeys: ["t", "a"],
    allKeys: [...HOME_ROW, "e", "i", "r", "u", "t", "a"],
    drills: [
      { type: "keys", content: "t a t a a t t a a t t a" },
      { type: "words", content: "la ta sa rat tarte salade malade date tasse haute" },
      { type: "words", content: "la salade est faite la date est juste il reste la" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 9,
    phase: 2,
    newKeys: ["o", "y", "z", "p"],
    allKeys: [...HOME_ROW, ...TOP_ROW],
    drills: [
      { type: "keys", content: "o y z p o y z p y o p z" },
      { type: "words", content: "pour poste porte type trop gros assez toujours groupe" },
      { type: "words", content: "il y a trop de pages le groupe passe par la porte" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 10,
    phase: 2,
    newKeys: [],
    allKeys: [...HOME_ROW, ...TOP_ROW],
    drills: [
      { type: "words", content: "propose apporte partage regarde repose ajoute figure" },
      { type: "words", content: "le groupe passe toujours par la porte" },
      { type: "words", content: "tu tapes juste et le reste suit assez de mots pour la suite" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  // === Phase 3: Rangée inférieure ===
  {
    id: 11,
    phase: 3,
    newKeys: ["n", "c"],
    allKeys: [...HOME_ROW, ...TOP_ROW, "n", "c"],
    drills: [
      { type: "keys", content: "n c n c c n n c c n n c" },
      { type: "words", content: "un une ne en on non nom chance cinq encore donc" },
      { type: "words", content: "on ne change rien chacun est content" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 12,
    phase: 3,
    newKeys: ["v", "b", ",", "."],
    allKeys: [...HOME_ROW, ...TOP_ROW, "n", "c", "v", "b", ",", "."],
    drills: [
      { type: "keys", content: "v b v b , . , . b v , ." },
      { type: "words", content: "vous bien brave bonne vendre novembre verbe avec" },
      { type: "sentences", content: "vous venez bien, merci. le verbe vient en second." },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 13,
    phase: 3,
    newKeys: ["w", "x", "é", "è", "à", "ç"],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "keys", content: "é è à ç w x é è à ç x w" },
      { type: "words", content: "été très à ça près après voilà leçon réussi wagon taxi" },
      { type: "sentences", content: "ça marche très bien. le résultat est exact." },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  // === Phase 4: Mots courants ===
  {
    id: 14,
    phase: 4,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "words", content: "le la les de des un une et est en que qui ne pas pour" },
      { type: "words", content: "dans ce il elle au aux du sur avec son ses plus par mais" },
      { type: "words", content: "nous vous ils elles cette ces leur tout tous comme aussi" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 15,
    phase: 4,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "words", content: "avoir faire dire aller voir savoir pouvoir vouloir venir devoir" },
      { type: "words", content: "temps jour homme femme monde vie main chose gens moment" },
      { type: "words", content: "grand petit bon seul jeune premier dernier autre nouveau vrai" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 16,
    phase: 4,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "words", content: "ouvrir fermer commencer lancer construire choisir régler" },
      { type: "words", content: "écran clavier souris dossier bouton révision numéro projet" },
      { type: "words", content: "ordinateur logiciel affichage réglages message document" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  // === Phase 5: Majuscules ===
  {
    id: 17,
    phase: 5,
    newKeys: ["Shift"],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "words", content: "Le La Les Un Une Et Pour Avec Dans Sur Nous Vous" },
      { type: "words", content: "Lundi Mardi Mercredi Jeudi Vendredi Samedi Dimanche" },
      { type: "sentences", content: "Paris est la capitale de la France. Lyon est plus au sud." },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 18,
    phase: 5,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "Anna écrit ses mails le matin. Jonas lit le rapport." },
      { type: "sentences", content: "Lundi nous lançons le projet. Vendredi il est fini." },
      { type: "sentences", content: "Berlin est en Allemagne. Genève est en Suisse." },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  // === Phase 6: Ponctuation ===
  {
    id: 19,
    phase: 6,
    newKeys: ["?", "!"],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "Tout est juste? Oui, ça marche. Voilà qui est fort!" },
      { type: "sentences", content: "Attends, quoi? Tu es certain? Oui! Je regarde." },
      { type: "sentences", content: "Bonjour à tous. Comment va la journée? Très bien, merci!" },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 20,
    phase: 6,
    newKeys: ["'", "\"", ":", "-"],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "C'est bon. J'ai fini. L'heure est venue." },
      { type: "sentences", content: "Elle dit : \"Bonjour.\" Il répond : \"Salut.\"" },
      { type: "sentences", content: "Le fait bien connu : c'est la pratique qui compte. Allez-y sans stress." },
    ],
    completionThreshold: 90,
    isFree: false,
  },
  {
    id: 21,
    phase: 6,
    newKeys: ["(", ")", "@", "&"],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "Envoie le tout à nom@email.fr pour relecture." },
      { type: "sentences", content: "Le résultat (voir plus bas) est clair & net." },
      { type: "sentences", content: "Appelle-nous (du lundi au vendredi) ou écris à info@societe.fr." },
    ],
    completionThreshold: 92,
    isFree: false,
  },
  // === Phase 7: Phrases + Paragraphes ===
  {
    id: 22,
    phase: 7,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "La meilleure façon d'apprendre est de pratiquer chaque jour." },
      { type: "sentences", content: "Un esprit clair et des doigts calmes font une frappe rapide." },
      { type: "sentences", content: "La précision d'abord. La vitesse suit toute seule." },
    ],
    completionThreshold: 92,
    isFree: false,
  },
  {
    id: 23,
    phase: 7,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "Bien écrire commence par bien taper. Quand les doigts courent sans réfléchir, la tête reste sur le message." },
      { type: "sentences", content: "La différence entre une frappe rapide et une frappe lente, ce n'est pas le talent. Ce sont des milliers de petites répétitions justes." },
      { type: "sentences", content: "Chaque mail, chaque message, chaque document construit ta vitesse. Taper est une compétence quotidienne." },
    ],
    completionThreshold: 92,
    isFree: false,
  },
  {
    id: 24,
    phase: 7,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "Notes de la réunion : nous avons discuté du nouveau calendrier. La date limite est en mars. Tout le monde valide la démarche. Les actions sont réparties dans l'équipe." },
      { type: "sentences", content: "Chère équipe, merci de lire le document joint avant notre point de jeudi. N'hésitez pas à m'écrire directement si vous avez des questions. J'attends vos retours avec plaisir." },
      { type: "sentences", content: "Le rapport trimestriel montre une forte croissance partout. Le chiffre d'affaires progresse de douze pour cent sur un an. La satisfaction client reste haute dans toutes les régions." },
    ],
    completionThreshold: 92,
    isFree: false,
  },
  // === Phase 8: Vitesse + Fluidité ===
  {
    id: 25,
    phase: 8,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "words", content: "le la les de des un une et est en que qui ne pas pour dans" },
      { type: "words", content: "ce il elle au aux du sur avec son ses plus par mais nous vous" },
      { type: "words", content: "ils elles cette ces leur tout tous comme aussi bien sans sous" },
    ],
    completionThreshold: 92,
    isFree: false,
  },
  {
    id: 26,
    phase: 8,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "La vitesse vient de la mémoire musculaire, pas de l'effort. Détends les mains et laisse les doigts travailler." },
      { type: "sentences", content: "Portez ce vieux whisky au juge blond qui fume. Voyez le brick géant que j'examine près du wharf." },
      { type: "sentences", content: "Taper, c'est comme le vélo. Une fois bien appris, ça ne se perd plus. La compétence reste pour la vie." },
    ],
    completionThreshold: 94,
    isFree: false,
  },
  {
    id: 27,
    phase: 8,
    newKeys: [],
    allKeys: [...ALL_LETTERS],
    drills: [
      { type: "sentences", content: "Un mail bien écrit fait gagner du temps à tout le monde. Bien écrire commence par bien taper. Qui tape vite pense plus librement." },
      { type: "sentences", content: "Le dernier test : tape ce paragraphe aussi vite et aussi juste que possible. Ne regarde pas le clavier. Fais confiance à tes doigts." },
      { type: "sentences", content: "Tu as fini toutes les leçons de ce cours. Tes doigts travaillent avec méthode. C'est ton nouveau standard. Va écrire quelque chose de grand." },
    ],
    completionThreshold: 94,
    isFree: false,
  },
];

export const meta: Record<number, LessonMeta> = {
  0: {
    title: "Trouve les repères",
    subtitle: "Regarde ton clavier : les touches F et J portent de petites bosses. Pose tes index dessus - gauche sur F, droite sur J. Depuis cette position, tu atteins toutes les autres touches.",
    newKeysLabel: "F et J",
    completionMessage: "Bien. Tes doigts savent maintenant où est leur place.",
    insight: "Les bosses sur F et J existent sur presque tous les claviers du monde - pour que tes doigts retrouvent leur position sans regarder. S'orienter à l'aveugle, c'est le principe de base de toute la méthode.",
  },
  1: {
    title: "F et J - tes ancres",
    subtitle: "Les deux touches les plus importantes. Tout part d'ici.",
    newKeysLabel: "F et J",
    completionMessage: "Base solide. On continue.",
    insight: "Ce n'est pas ta conscience qui apprend à taper, c'est ton cervelet. Chaque répétition correcte construit un chemin moteur. D'où la règle : lentement et juste maintenant, vite et sans y penser plus tard.",
  },
  2: {
    title: "D et K en plus",
    subtitle: "Majeur gauche sur D, majeur droit sur K.",
    newKeysLabel: "D et K",
    completionMessage: "Quatre doigts au travail. Ça roule.",
    insight: "Pourquoi tant de répétitions ? La myéline. À chaque répétition, ton corps isole davantage le circuit nerveux utilisé - le signal devient mesurablement plus rapide. S'entraîner, c'est littéralement câbler.",
  },
  3: {
    title: "S et L en plus",
    subtitle: "Annulaire gauche sur S, annulaire droit sur L.",
    newKeysLabel: "S et L",
    completionMessage: "Six doigts actifs. La rangée de base grandit.",
    insight: "La précision avant la vitesse - ce n'est pas un slogan. Les erreurs s'entraînent aussi bien que les réussites. Qui pratique vite et faux automatise ses fautes en même temps.",
  },
  4: {
    title: "Q et M en plus",
    subtitle: "Auriculaire gauche sur Q, auriculaire droit sur M.",
    newKeysLabel: "Q et M",
    completionMessage: "Les auriculaires sont de la partie.",
    insight: "Les auriculaires te semblent maladroits ? Tout à fait normal. Ce sont les doigts les moins entraînés du quotidien. Ça passe plus vite que tu ne le crois.",
  },
  5: {
    title: "G et H - le centre",
    subtitle: "Les deux index s'étirent vers le centre. La rangée de base est complète.",
    newKeysLabel: "G et H",
    completionMessage: "Rangée de base maîtrisée. C'est le socle de tout le reste.",
    insight: "Particularité AZERTY : la rangée de base ne contient aucune voyelle. Les vrais mots arrivent à la prochaine leçon - là, tout s'ouvre d'un coup. Tiens bon.",
  },
  6: {
    title: "E et I - les incontournables",
    subtitle: "Index et majeur montent vers la rangée du haut.",
    newKeysLabel: "E et I",
    completionMessage: "Le E est à toi - la lettre la plus fréquente du français.",
    insight: "Le E représente environ 15 pour cent de toutes les lettres en français - champion absolu. À partir de cette leçon, tu tapes de vrais mots, et ton cerveau passe des lettres aux motifs.",
  },
  7: {
    title: "R et U en plus",
    subtitle: "Les index prennent la rangée supérieure.",
    newKeysLabel: "R et U",
    completionMessage: "Ton vocabulaire grandit à chaque leçon.",
    insight: "Le chunking : ton cerveau regroupe les suites de lettres en unités. Bientôt tu taperas \"sur\" non pas comme s-u-r, mais comme un seul geste. C'est là que naît la vitesse.",
  },
  8: {
    title: "T et A en plus",
    subtitle: "Le A - enfin ! Sur AZERTY, il habite la rangée du haut.",
    newKeysLabel: "T et A",
    completionMessage: "Avec le A, le français s'ouvre en grand.",
    insight: "Si aujourd'hui semble plus dur qu'hier : bon signe. Ton cerveau consolide en arrière-plan, surtout pendant le sommeil. Un plateau n'est pas un arrêt, c'est une consolidation.",
  },
  9: {
    title: "O, Y, Z et P",
    subtitle: "Le reste de la rangée supérieure d'un coup.",
    newKeysLabel: "O, Y, Z, P",
    completionMessage: "Rangée supérieure complète. Deux tiers du clavier sont à toi.",
    insight: "15 minutes par jour battent largement 2 heures le dimanche. La raison s'appelle l'effet d'espacement : les nuits entre les séances fixent ce que tu as appris. Ton sommeil s'entraîne avec toi.",
  },
  10: {
    title: "Consolider la rangée du haut",
    subtitle: "Rangée de base plus rangée supérieure. Des suites de mots fluides.",
    newKeysLabel: "Révision",
    completionMessage: "À l'aise sur deux rangées. La rangée du bas attend.",
    insight: "Le moment le plus important du cours : résiste à l'envie de regarder le clavier. Chaque coup d'œil interrompt la construction du repérage à l'aveugle - et c'est exactement lui, l'objectif.",
  },
  11: {
    title: "N et C en plus",
    subtitle: "L'index et le majeur descendent vers la rangée du bas.",
    newKeysLabel: "N et C",
    completionMessage: "N et C en place. Les textes français s'ouvrent.",
    insight: "Avec le N et le C, tu couvres une grande partie des mots français les plus courants : un, une, on, en, donc, encore. Environ 80 pour cent des textes du quotidien sont maintenant à ta portée.",
  },
  12: {
    title: "V, B et la ponctuation",
    subtitle: "Virgule et point - tes phrases prennent forme.",
    newKeysLabel: "V, B, virgule, point",
    completionMessage: "Tu peux maintenant taper des phrases complètes et ponctuées.",
    insight: "Remarquer une erreur, c'est apprendre : à l'instant où tu sens que le doigt s'est trompé, ton cerveau met sa carte à jour. Corriger consciemment vaut mieux que continuer en force.",
  },
  13: {
    title: "Les accents : é, è, à, ç",
    subtitle: "La grande force de l'AZERTY : les accents ont leurs propres touches.",
    newKeysLabel: "W, X, é, è, à, ç",
    completionMessage: "Les accents t'obéissent. Tout le français est possible.",
    insight: "Taper les accents à l'aveugle, c'est la discipline reine sur AZERTY - la plupart des autodidactes n'y arrivent jamais. À partir d'aujourd'hui, tu fais partie de la minorité qui sait.",
  },
  14: {
    title: "Les mots les plus fréquents",
    subtitle: "Les mots que tu tapes le plus. Vite et sans faute.",
    newKeysLabel: "Mots courants",
    completionMessage: "Ces mots sont en place. Tes textes du quotidien accélèrent.",
    insight: "Les 100 mots les plus fréquents représentent environ la moitié de chaque texte français. Automatiser exactement ces mots, c'est le plus grand bond de vitesse de tout le cours.",
  },
  15: {
    title: "Encore plus de mots du quotidien",
    subtitle: "Verbes, noms, adjectifs - le ciment de chaque phrase.",
    newKeysLabel: "Mots courants",
    completionMessage: "Le vocabulaire de base coule tout seul.",
    insight: "L'automatisation, c'est quand ton cerveau ne vérifie plus chaque lettre mais déclenche la séquence entière d'un coup. C'est exactement ce qui arrive à ces mots en ce moment.",
  },
  16: {
    title: "Vocabulaire de bureau",
    subtitle: "Les mots de ton quotidien professionnel.",
    newKeysLabel: "Mots du quotidien",
    completionMessage: "Ton vocabulaire de travail est en place.",
    insight: "Effet de transfert : ce que tu pratiques ici, ce sont exactement les mots de tes vrais mails et documents. Chaque minute d'entraînement paie désormais directement sur ta journée de travail.",
  },
  17: {
    title: "Majuscules avec Shift",
    subtitle: "La touche Maj - toujours avec la main opposée.",
    newKeysLabel: "Maj",
    completionMessage: "Les majuscules sont en place. Tes phrases ont fière allure.",
    insight: "La règle des pros pour Maj : toujours la main opposée. Un A majuscule ? L'auriculaire droit tient Maj, la gauche tape le A. Ainsi, aucune main ne se bloque.",
  },
  18: {
    title: "Phrases avec majuscules",
    subtitle: "Noms, débuts de phrase - comme dans un vrai texte.",
    newKeysLabel: "Révision",
    completionMessage: "Les majuscules coulent de source. C'est le but.",
    insight: "Chaque phrase française commence par une majuscule - ton entraînement Maj tourne ici en continu, sans que tu y penses. L'automatisme s'installe tout seul.",
  },
  19: {
    title: "Question et exclamation",
    subtitle: "Point d'interrogation et point d'exclamation dans le flux.",
    newKeysLabel: "? et !",
    completionMessage: "Tes phrases ont maintenant une voix.",
    insight: "Écrire avec fluidité, c'est ne plus buter sur la ponctuation. La micro-pause avant le point coûte du temps à chaque phrase aux non-entraînés - les pros tapent sans s'arrêter. Bientôt toi aussi.",
  },
  20: {
    title: "Apostrophe, guillemets et deux-points",
    subtitle: "Les subtilités des textes français - l'apostrophe partout.",
    newKeysLabel: "' \" : -",
    completionMessage: "C'est, j'ai, l'heure - l'apostrophe t'obéit.",
    insight: "Le français est la langue de l'apostrophe : c'est, j'ai, l'heure, d'accord. Elle revient si souvent que la maîtriser à l'aveugle change ta fluidité du tout au tout.",
  },
  21: {
    title: "Parenthèses, @ et compagnie",
    subtitle: "Les caractères spéciaux des mails et textes techniques.",
    newKeysLabel: "( ) @ &",
    completionMessage: "Les adresses mail, tu les tapes maintenant à l'aveugle.",
    insight: "L'arobase et les parenthèses sont les touches du bureau par excellence. Qui les trouve à l'aveugle écrit adresses et références sans perdre le fil de sa lecture.",
  },
  22: {
    title: "Phrases fluides",
    subtitle: "Des pensées entières d'un trait, phrase après phrase.",
    newKeysLabel: "Phrases",
    completionMessage: "Les phrases coulent. Les paragraphes sont la prochaine étape.",
    insight: "Quand peux-tu \"écrire librement\" ? Règle simple : quand ta précision dépasse 95 pour cent sur tout l'alphabet, tu penses en phrases et non plus en touches. Tu es plus près que tu ne le crois.",
  },
  23: {
    title: "Paragraphes plus longs",
    subtitle: "Garder la concentration sur plusieurs phrases.",
    newKeysLabel: "Paragraphes",
    completionMessage: "Tu tiens la concentration sur des textes longs.",
    insight: "L'endurance est une compétence à part. Les exercices courts entraînent la précision, les longs paragraphes entraînent la tenue - les deux ensemble font l'aisance au quotidien.",
  },
  24: {
    title: "Vrais textes de travail",
    subtitle: "Notes de réunion, mails d'équipe, rapports - ton quotidien comme exercice.",
    newKeysLabel: "Textes pratiques",
    completionMessage: "Ce n'était plus un exercice. C'était du travail - et ça a roulé.",
    insight: "Les vrais textes de travail contiennent des chiffres, des noms, des deux-points et des virgules aux endroits inconfortables. C'est exactement pour ça que tu les pratiques ici - ton entraînement devient identique à ton quotidien.",
  },
  25: {
    title: "Tours de vitesse",
    subtitle: "Les mots les plus fréquents, aussi vite que tu peux.",
    newKeysLabel: "Vitesse",
    completionMessage: "C'était rapide. Et ça va encore accélérer.",
    insight: "Maintenant tu peux lâcher prise : au-dessus de 95 pour cent de précision, l'accélération consciente est au programme. Si le taux d'erreur monte un peu, c'est prévu - il se stabilise plus haut.",
  },
  26: {
    title: "Pangrammes",
    subtitle: "Des phrases avec toutes les lettres de l'alphabet.",
    newKeysLabel: "Toutes les touches",
    completionMessage: "Tout l'alphabet en mouvement. Impressionnant.",
    insight: "Les pangrammes contiennent chaque lettre de l'alphabet au moins une fois - l'entraînement complet du clavier. \"Portez ce vieux whisky au juge blond qui fume\" est le classique français.",
  },
  27: {
    title: "La dernière touche",
    subtitle: "Pleine vitesse, pleine précision. Montre ce que tu sais faire.",
    newKeysLabel: "Final",
    completionMessage: "Cours terminé. Tes doigts travaillent maintenant avec méthode.",
    insight: "Terminé veut dire : l'automatisation est en place. Désormais, chaque mail est un entraînement - ta courbe continue de monter pendant des mois, sans plan d'exercice. Exactement comme prévu.",
  },
};
